#!/bin/bash

# Run install_git_hooks.sh to enable this Git hook

# Invariant 1: All tests in `core` must pass
cargo test \
 --package swanky-adversary \
 --package swanky-channel \
 --package swanky-error \
 --package swanky-party \
 --package swanky-serialization \
 --package vectoreyes \
 --lib
