#!/bin/sh

# Copy this file into `.git/hooks/` to enable its use:
#  `$> cp etc/hooks/* .git/hooks`

# Invariant 1: We want to run the formatter and linter for Swanky before every commit
./swanky lint # Note that `./swanky link` runs `./swanky fmt --check`

# Invariant 2: We want to not have any Clippy errors prior to a commit
cargo clippy --all-targets -- -Dwarnings # Warnings are considered errors
