#!/bin/sh

# Copy this file into `.git/hooks/` to enable its use:
#  `$> cp etc/hooks/* .git/hooks`

# Invariant 1: All tests in `core` must pass
cargo test \
 --package swanky-error \
 --package vectoreyes \
 --lib
