# Choosing this becuase it comes with Rust pre-installed.
image: artifactory.galois.com:5018/rust:1.84.0

format:
  tags: [stardust, Linux]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cargo fmt -p schmivitz --check
    - cargo clippy -p schmivitz

test:
  tags: [stardust, Linux]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cargo build -p schmivitz
    - cargo test -p schmivitz

doc:
  tags: [stardust, Linux]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cargo doc -p schmivitz
