#![deny(missing_docs)]
//! Hooks for testing malicious behavior in various cryptographic protocols.

use std::{cell::RefCell, thread::LocalKey};

/// Create a new entry point for testing malicious behavior.
///
/// An entry point allows a test to replace a specific value in a protocol with
/// a different value. This allows for testing possible malicious behavior on
/// the part of various parties in the protocol.
///
/// # Example
/// ```ignore
/// new_entry_point!(SENDER_MSG, u128);
/// ```
/// This creates a new entry point called `SENDER_MSG` which will replace a
/// value of type `u128`.
#[macro_export]
macro_rules! new_entry_point {
    ($name: ident, $typ: ty) => {
        std::thread_local! {
            pub static $name: std::cell::RefCell<Option<Box<dyn FnMut($typ) -> $typ>>> =
                const { std::cell::RefCell::new(None) };
        }
    };
}

/// Add an entry point for testing malicious behavior.
///
/// This allows a particular variable in the protocol implementation to be
/// replaced by a variable generated by the entry point.
///
/// # Example
/// ```ignore
/// let msg = test_entry_point(msg, SENDER_MSG);
/// ```
/// This outputs the value generated by the entry point `SENDER_MSG` on `msg`.
pub fn test_entry_point<T>(
    var: T,
    entry: &'static LocalKey<RefCell<Option<Box<dyn FnMut(T) -> T>>>>,
) -> T {
    entry.with(|hook| {
        if let Some(hook) = hook.borrow_mut().as_mut() {
            hook(var)
        } else {
            var
        }
    })
}

/// Runs an entry point for testing malicious behavior.
///
/// This runs the protocol, as specified by `func`, using `hook` to modify the
/// value specified by `entry`.
///
/// # Example
/// ```ignore
/// run_with_entry_point(f, hook, SENDER_MSG);
/// ```
/// This runs `f`, replacing the value at the entry point `SENDER_MSG` with
/// the output of `hook`.
pub fn run_with_entry_point<T, U, F: FnMut() -> T, G: FnMut(U) -> U + 'static>(
    mut func: F,
    hook: G,
    entry: &'static LocalKey<RefCell<Option<Box<dyn FnMut(U) -> U>>>>,
) -> T {
    entry.with(|entry| {
        let old = entry.take();
        // Insert the hook before running `func`.
        *entry.borrow_mut() = Some(Box::new(hook));
        let out = func();
        // Insert back the original hook to avoid issues when running other tests.
        entry.replace(old);
        out
    })
}
