[package]
name = "swanky-ocelot-error"
description = "[DEPRECATED] An error type used by crates formerly contained in ocelot"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-cointoss.workspace = true

