/*! Cryptographic primitives used for VOLE-it-HEAD */
use crate::parameters::SECURITY_PARAM;
use crate::vole::commit_reconstruct::{Corrections, corrections_to_bytes};
use aes::Aes128;
use aes::cipher::{
    BlockEncrypt, KeyInit,
    generic_array::{GenericArray, typenum::U16},
};
use sha3::digest::{ExtendableOutput, Update, XofReader};
use shake::Shake128;
#[cfg(test)]
use swanky_field_binary::F2;
use swanky_field_binary::F128b;
use swanky_serialization::CanonicalSerialize;

/// Initialization Vector.
pub type IV = [u8; 16];
/// Key as found in the internal nodes of the Tree-PRG/GGM-tree.
pub(crate) type Key = [u8; SECURITY_PARAM / 8];
/// Commitment as generated by 1-VC.
pub(crate) type Com = [u8; (SECURITY_PARAM * 2) / 8];
/// Seed generated by 1-VC.
pub(crate) type Seed = [u8; SECURITY_PARAM / 8];

/// Pseudo random generator, specialized to 1-VC.
///
/// In general a PRG generates a stream of randomness, but the 1-VC scheme only needs
/// the PRG to generate 2 random keys from a key in the GGM tree.
/// Therefore its interface is specialized to this with the [`PRG::encrypt_double()`] function.
#[allow(clippy::upper_case_acronyms)]
pub(crate) struct PRG {
    aes0: Aes128,
    counter: u128,
}

impl PRG {
    /// Create a PRG from an an initialization vector `iv`.
    pub(crate) fn new(seed: IV, iv: IV) -> Self {
        let key: GenericArray<u8, _> = GenericArray::from(seed);
        let aes0 = Aes128::new(&key);

        let counter = u128::from_le_bytes(iv);
        Self { aes0, counter }
    }

    fn incr(&mut self) {
        self.counter += 1;
    }

    fn counter_to_bytes(&self) -> [u8; 16] {
        self.counter.to_le_bytes()
    }

    /// Function that returns two random keys.
    /// There has no associated decrypt function, it is used for its PRG properties.
    /// This function corresponds to `PRG.encrypt` in the spec.
    pub(crate) fn encrypt_double(&mut self) -> (Key, Key) {
        const BLOCKS: usize = 2;
        let block = GenericArray::from([0u8; 16]);
        let mut blocks = [block; BLOCKS];

        // encrypt blocks in place
        for block in blocks.iter_mut() {
            *block = GenericArray::from(self.counter_to_bytes());
            self.incr();
        }
        self.aes0.encrypt_blocks(&mut blocks);

        let k1 = blocks[0].into();
        let k2 = blocks[1].into();
        (k1, k2)
    }

    /// Function that returns a pseudo-random vector of F2 values
    #[cfg(test)]
    pub(crate) fn prg(mut self, l: usize) -> Vec<F2> {
        let mut res = Vec::with_capacity(l);

        let mut remaining: i64 = l.try_into().unwrap();

        const BLOCKS: usize = 16;
        let block = GenericArray::from([0u8; 16]);
        let mut blocks = [block; BLOCKS];
        while remaining > 0 {
            // encrypt blocks in place
            for block in blocks.iter_mut() {
                *block = GenericArray::from(self.counter_to_bytes());
                self.incr();
            }
            self.aes0.encrypt_blocks(&mut blocks);

            // converting blocks to F2 values and pushing them into the vector.
            for block in blocks.iter() {
                for u in block.iter() {
                    for i in 0..8u8 {
                        if remaining <= 0 {
                            return res;
                        }

                        res.push(((u >> i & 1_u8) == 1).into());
                        remaining -= 1;
                    }
                }
            }
        }

        res
    }

    /// Pseudo-random generate seeds to initialize other pseudo-random generators.
    ///
    /// This is mostly a convenience function as it could be derived from [`PRG`].
    pub(crate) fn generate_prg_seeds(mut self, repetition_param: usize) -> Vec<Seed> {
        let mut res = Vec::with_capacity(repetition_param);

        for _ in 0..repetition_param {
            let mut block = GenericArray::from(self.counter_to_bytes());
            self.aes0.encrypt_block(&mut block);
            self.incr();

            res.push(block.into());
        }
        res
    }
}

/// Constant defining the number of blocks used by the PRG stream structure.
const NUM_BLOCKS: usize = 8;

#[allow(clippy::upper_case_acronyms)]
#[allow(non_camel_case_types)]
/// Pseudo random generator stream structure.
///
/// The bits are packed into `u64`. If the last `u64` has a capacity to contain more
/// bits than requested with `l` then the user of this function is in charge to ignore
/// the bits.
pub(crate) struct PRG_Stream {
    aes0: Aes128,
    counter: u128,
    blocks: [GenericArray<u8, U16>; NUM_BLOCKS],
    block_number: usize,
    pos_in_block: usize,
    is_dummy: bool,
}

impl Default for PRG_Stream {
    fn default() -> Self {
        PRG_Stream::new_dummy([0u8; 16], [0u8; 16])
    }
}

impl PRG_Stream {
    /// Create a PRG from an an initialization vector `iv`.
    pub(crate) fn new(seed: IV, iv: IV) -> Self {
        let key: GenericArray<u8, _> = GenericArray::from(seed);
        let aes0 = Aes128::new(&key);

        let counter = u128::from_le_bytes(iv);
        Self {
            aes0,
            counter,
            block_number: NUM_BLOCKS, // starting at the max instead of 0 so that `next()` triggers a refill
            blocks: [GenericArray::from([0u8; 16]); NUM_BLOCKS],
            pos_in_block: 0,
            is_dummy: false,
        }
    }

    /// Create a dummy prg that always returns 0s.
    pub(crate) fn new_dummy(seed: IV, iv: IV) -> Self {
        let key: GenericArray<u8, _> = GenericArray::from(seed);
        let aes0 = Aes128::new(&key);

        let counter = u128::from_le_bytes(iv);
        Self {
            aes0,
            counter,
            block_number: NUM_BLOCKS,
            blocks: [GenericArray::from([0u8; 16]); NUM_BLOCKS],
            pos_in_block: 0,
            is_dummy: true,
        }
    }

    fn incr(&mut self) {
        self.counter += 1;
    }

    fn counter_to_bytes(&self) -> [u8; 16] {
        self.counter.to_le_bytes()
    }

    /// Returns the next 64 pseudo-random bits from the stream as a little-endian u64,
    /// refilling the AES-backed block buffer as needed.
    pub(crate) fn prg_next(&mut self) -> u64 {
        // When the PRG is dummy it always return 0s.
        if self.is_dummy {
            return 0u64;
        }
        if self.block_number == NUM_BLOCKS {
            self.prg_refill();
        }
        let mut t: [u8; 8] = Default::default();
        let block = &self.blocks[self.block_number];
        if self.pos_in_block == 0 {
            t.clone_from_slice(&block[0..8]);
            self.pos_in_block = 8;
        } else {
            t.clone_from_slice(&block[8..16]);
            // move to next block
            // it is possible that the next block does not exist but that will
            // be fixed at the next call
            self.pos_in_block = 0;
            self.block_number += 1;
        };
        u64::from_le_bytes(t)
    }

    #[inline(always)]
    fn prg_refill(&mut self) {
        // encrypt blocks in place
        for i in 0..NUM_BLOCKS {
            self.blocks[i] = GenericArray::from(self.counter_to_bytes());
            self.incr();
        }
        self.block_number = 0;
        self.pos_in_block = 0; // done elsewhere

        // NOTE: this encryption here is a bottleneck,
        // delete this line and you would see the performance of convert_to_vole improve dramatically, say 10x .
        self.aes0.encrypt_blocks(&mut self.blocks);
    }
}

#[cfg(test)]
mod tests {
    use super::{IV, PRG, PRG_Stream};
    use swanky_field_binary::F2;

    #[test]
    fn prg_matches_stream_bits() {
        let seed: IV = [5u8; 16];
        let iv: IV = [11u8; 16];

        let lengths = [
            1usize, 7, 8, 63, 64, 65, 127, 128, 129, 511, 512, 513, 1023, 1024, 1025, 2047, 2048,
            2049, 100000, 1048575, 1048576, 1048577,
        ];
        for &l in &lengths {
            let expected_bits = PRG::new(seed, iv).prg(l);
            let mut stream = PRG_Stream::new(seed, iv);
            let mut stream_bits = Vec::with_capacity(l);
            while stream_bits.len() < l {
                let block = stream.prg_next();
                for i in 0..64 {
                    if stream_bits.len() == l {
                        break;
                    }
                    let bit = ((block >> i) & 1) == 1;
                    stream_bits.push(F2::from(bit));
                }
            }
            assert_eq!(expected_bits, stream_bits, "bit mismatch for l={}", l);
        }
    }
}

/// Hash function that generates a [`Seed`] and a [`Com`]mitment from a [`Key`] and an initialization vector [`IV`].
///
/// This function is applied on the leaves keys of the Tree-PRG/GGM-tree to generate the seeds and commitments.
/// This function corresponds to the H0 in the FAEST spec, defined page 16.
pub(crate) fn h0(x: Key, iv: IV) -> (Seed, Com) {
    // Hash x||iv to generate the Key
    let mut hasher = Shake128::default();
    hasher.update(&x);
    hasher.update(&iv);
    hasher.update(&[0u8]);

    let mut reader = hasher.finalize_xof();
    let mut seed = [u8::default(); SECURITY_PARAM / 8];
    let mut commitment = [u8::default(); (SECURITY_PARAM * 2) / 8];
    reader.read(seed.as_mut_slice());
    reader.read(commitment.as_mut_slice());

    (seed, commitment)
}

/// Length of H1 hash in bytes.
pub(crate) const H1_LENGTH: usize = (SECURITY_PARAM / 8) * 2;

/// Hash digest for a collision-resistant hash function.
///
/// This is used for various purposes throughout the protocol.
#[derive(Clone, Copy, Default)]
pub(crate) struct H1([u8; H1_LENGTH]);

impl H1 {
    /// Compute the [`H1`] hash from input bytes.
    pub(crate) fn from_bytes(inp: &[u8]) -> H1 {
        let mut out = H1::default();

        let mut hasher = Shake128::default();
        hasher.update(inp);
        hasher.update(&[1u8]);

        hasher.finalize_xof_into(&mut out.0);
        out
    }

    /// Treat this hash digest as a commitment.
    pub(crate) fn into_com(self) -> Com {
        self.0
    }
}

impl AsRef<[u8; H1_LENGTH]> for H1 {
    fn as_ref(&self) -> &[u8; H1_LENGTH] {
        &self.0
    }
}

/// Hash function for the Fiat-Shamir challenges generated in the protocol.
///
/// This is `$H_2^j$` in FAEST spec
#[derive(Default)]
struct H2Hasher(Shake128);

impl H2Hasher {
    fn update(&mut self, data: &[u8]) {
        self.0.update(data);
    }

    fn finalize(mut self, out: &mut [u8]) {
        self.0.update(&[2u8]);
        self.0.finalize_xof_into(out);
    }
}

/// Length of 1st challenge in bytes.
pub(crate) const CHALL1_LENGTH: usize = (SECURITY_PARAM * 6) / 8;

/// First challenge
pub(crate) type Chall1 = [u8; CHALL1_LENGTH];

/// Make the first Fiat-Shamir challenge.
///
/// This computes `$H_2^1$` in FAEST spec.
pub(crate) fn h2_chall1(mu: &H1, hcom: &Com, corrections: &Corrections, iv: &IV) -> Chall1 {
    let mut hasher = H2Hasher::default();

    hasher.update(&mu.0);
    hasher.update(hcom);
    hasher.update(&corrections_to_bytes(corrections));
    hasher.update(iv);

    let mut out = [0u8; CHALL1_LENGTH];
    hasher.finalize(&mut out);
    out
}

/// Length of 2nd challenge in bytes.
pub(crate) const CHALL2_LENGTH: usize = (SECURITY_PARAM * 3 + 64) / 8;
/// Second challenge
pub(crate) type Chall2 = [u8; CHALL2_LENGTH];

/// This is `$H_2^2$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h_chall2(inp: &[u8]) -> Chall2 {
    let mut hasher = H2Hasher::default();

    hasher.update(inp);

    let mut out: Chall2 = [0u8; CHALL2_LENGTH]; // NOTE: default does not work here
    hasher.finalize(&mut out);
    out
}

/// Length of 3rd challenge in bytes.
pub(crate) const CHALL3_LENGTH: usize = SECURITY_PARAM / 8;
/// Third challenge.
pub(crate) type Chall3 = [u8; CHALL3_LENGTH];

/// Makes the third Fiat-Shamir challenge.
///
/// This computes `$H_2^3$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h2_chall3(chall2: &Chall2, a_tilde: &F128b, b_tilde: &F128b) -> Chall3 {
    let mut hasher = H2Hasher::default();

    hasher.update(chall2);
    hasher.update(&a_tilde.to_bytes());
    hasher.update(&b_tilde.to_bytes());

    let mut out = Chall3::default();
    hasher.finalize(&mut out);
    out
}

/// Hash digest for randomness and IV generation.
///
/// This should incorporate secret information or randomness (e.g. that only
/// the verifier knows), to derive secret, per-proof values.
#[derive(Clone, Default)]
pub(crate) struct H3([u8; (SECURITY_PARAM + 128) / 8]);

impl H3 {
    /// Derive the [`H3`] hash from an input.
    #[allow(unused)]
    pub(crate) fn from_input(inp: &[u8]) -> Self {
        let mut hasher = Shake128::default();
        hasher.update(inp);

        // Append 0x3 for domain separation
        hasher.update(&[3u8]);
        let mut reader = hasher.finalize_xof();

        let mut out: H3 = Default::default();
        reader.read(out.as_mut());
        out
    }

    /// Derive the [`H3`] hash from an instance of `Shake128`, which we assume
    /// has already been updated with all relevant secret information.
    pub(crate) fn from_xof(mut xof: Shake128) -> Self {
        // Append 0x3 for domain separation
        xof.update(&[3u8]);

        let mut out: H3 = Default::default();
        xof.finalize_xof_into(out.as_mut());
        out
    }
}

impl AsRef<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_ref(&self) -> &[u8; SECURITY_PARAM / 8 + 128 / 8] {
        &self.0
    }
}

impl AsMut<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_mut(&mut self) -> &mut [u8; SECURITY_PARAM / 8 + 128 / 8] {
        &mut self.0
    }
}
