[package]
name = "swanky-authenticated-garbling"
description = "Authenticated malicious garbling in the presence of a malicious garbler and evaluator"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
fancy-garbling.workspace = true
swanky-authenticated-bits.workspace = true
swanky-field.workspace = true
swanky-field-binary.workspace = true
swanky-f-rand.workspace = true
swanky-channel.workspace = true
swanky-party.workspace = true
swanky-ot-traits.workspace = true
swanky-adversary.workspace = true
swanky-rng.workspace = true
swanky-error.workspace = true
swanky-ot-alsz-kos.workspace = true

vectoreyes.workspace = true
rand.workspace = true
itertools.workspace = true
proptest.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true


[[bench]]
name = "main"
harness = false