[package]
name = "swanky-authenticated-bits"
description = "A package for generating authenticated bits"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-ot-traits.workspace = true
swanky-adversary.workspace = true
swanky-party.workspace = true
swanky-channel.workspace = true
swanky-field-binary.workspace = true
swanky-field.workspace = true
swanky-serialization.workspace = true
swanky-aes-hash.workspace = true
swanky-aes-rng.workspace = true
vectoreyes.workspace = true

itertools.workspace = true
rand.workspace = true
proptest.workspace = true
eyre.workspace = true

[dev-dependencies]
swanky-ot-alsz-kos.workspace = true
