[package]
name = "swanky-oprf-kkrt"
description = "An implementation of the kkrt OPRF protocol"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
swanky-bytearray-utils.workspace = true
swanky-ot-alsz-kos.workspace = true
swanky-ot-traits.workspace = true
swanky-cointoss.workspace = true
swanky-ocelot-error.workspace = true
swanky-channel-legacy.workspace = true
swanky-oprf-traits.workspace = true
swanky-block.workspace = true
vectoreyes.workspace = true
rand.workspace = true
swanky-adversary.workspace = true
swanky-deprecated-bitwise-utils.workspace = true
swanky-bit-matrix-transpose.workspace = true
swanky-rng.workspace = true

