/*! Cryptographic primitives used for VOLE-it-HEAD */
use crate::parameters::SECURITY_PARAM;
use crate::vole::commit_reconstruct::{corrections_to_bytes, Corrections};
use aes::cipher::{generic_array::GenericArray, BlockEncrypt, KeyInit};
use aes::Aes128;
use sha3::{
    digest::{ExtendableOutput, Update, XofReader},
    Shake128,
};
use swanky_field_binary::F128b;
#[cfg(test)]
use swanky_field_binary::F2;
use swanky_serialization::CanonicalSerialize;

/// Initialization Vector.
pub type IV = [u8; 16];
/// Key as found in the internal nodes of the Tree-PRG/GGM-tree.
pub(crate) type Key = [u8; SECURITY_PARAM / 8];
/// Commitment as generated by 1-VC.
pub(crate) type Com = [u8; (SECURITY_PARAM * 2) / 8];
/// Seed generated by 1-VC.
pub(crate) type Seed = [u8; SECURITY_PARAM / 8];

/// Pseudo random generator, specialized to 1-VC.
///
/// In general a PRG generates a stream of randomness, but the 1-VC scheme only needs
/// the PRG to generate 2 random keys from a key in the GGM tree.
/// Therefore its interface is specialized to this with the [`PRG::encrypt_double()`] function.
#[allow(clippy::upper_case_acronyms)]
pub(crate) struct PRG {
    aes0: Aes128,
    counter: u128,
}

impl PRG {
    /// Create a PRG from an an initialization vector `iv`.
    pub(crate) fn new(seed: IV, iv: IV) -> Self {
        let key: GenericArray<u8, _> = GenericArray::from(seed);
        let aes0 = Aes128::new(&key);

        let counter = u128::from_le_bytes(iv);
        Self { aes0, counter }
    }

    fn incr(&mut self) {
        self.counter += 1;
    }

    fn counter_to_bytes(&self) -> [u8; 16] {
        self.counter.to_le_bytes()
    }

    /// Function that returns two random keys.
    /// There has no associated decrypt function, it is used for its PRG properties.
    /// This function corresponds to `PRG.encrypt` in the spec.
    pub(crate) fn encrypt_double(&mut self) -> (Key, Key) {
        const BLOCKS: usize = 2;
        let block = GenericArray::from([0u8; 16]);
        let mut blocks = [block; BLOCKS];

        // encrypt blocks in place
        for block in blocks.iter_mut() {
            *block = GenericArray::from(self.counter_to_bytes());
            self.incr();
        }
        self.aes0.encrypt_blocks(&mut blocks);

        let k1 = blocks[0].into();
        let k2 = blocks[1].into();
        (k1, k2)
    }

    /// Function that returns a pseudo-random vector of F2 values
    #[cfg(test)]
    pub(crate) fn prg(mut self, l: usize) -> Vec<F2> {
        let mut res = Vec::with_capacity(l);

        let mut remaining: i64 = l.try_into().unwrap();

        const BLOCKS: usize = 16;
        let block = GenericArray::from([0u8; 16]);
        let mut blocks = [block; BLOCKS];
        while remaining > 0 {
            // encrypt blocks in place
            for block in blocks.iter_mut() {
                *block = GenericArray::from(self.counter_to_bytes());
                self.incr();
            }
            self.aes0.encrypt_blocks(&mut blocks);

            // converting blocks to F2 values and pushing them into the vector.
            for block in blocks.iter() {
                for u in block.iter() {
                    for i in 0..8u8 {
                        if remaining <= 0 {
                            return res;
                        }

                        res.push(((u >> i & 1_u8) == 1).into());
                        remaining -= 1;
                    }
                }
            }
        }

        res
    }

    /// Function that returns a pseudo-random vector of bits
    ///
    /// The bits are packed into `u64`. If the last `u64` has a capacity to contain more
    /// bits than requested with `l` then the user of this function is in charge to ignore
    /// the bits.
    pub(crate) fn prg_compact(mut self, l: usize) -> Vec<u64> {
        let mut res = Vec::with_capacity(l / 64 + 1);

        // using i64 to allow for negative numbers
        let mut remaining: i64 = l.try_into().unwrap();

        const BLOCKS: usize = 16;
        let block = GenericArray::from([0u8; 16]);
        let mut blocks = [block; BLOCKS];
        while remaining > 0 {
            // encrypt blocks in place
            for block in blocks.iter_mut() {
                *block = GenericArray::from(self.counter_to_bytes());
                self.incr();
            }
            self.aes0.encrypt_blocks(&mut blocks);

            // moving blocks to u64 values and pushing them into the vector.
            for block in blocks.iter() {
                let mut t: [u8; 8] = Default::default();

                // Move 64 bits
                t.clone_from_slice(&block[0..8]);
                let u1 = u64::from_le_bytes(t);
                res.push(u1);
                remaining -= 64;
                if remaining <= 0 {
                    return res;
                }

                // Move another 64 bits
                t.clone_from_slice(&block[8..16]);
                let u1 = u64::from_le_bytes(t);
                res.push(u1);
                remaining -= 64;
                if remaining <= 0 {
                    return res;
                }
            }
        }

        res
    }

    /// Pseudo-random generate seeds to initialize other pseudo-random generators.
    ///
    /// This is mostly a convenience function as it could be derived from [`PRG`].
    pub(crate) fn generate_prg_seeds(mut self, repetition_param: usize) -> Vec<Seed> {
        let mut res = Vec::with_capacity(repetition_param);

        for _ in 0..repetition_param {
            let mut block = GenericArray::from(self.counter_to_bytes());
            self.aes0.encrypt_block(&mut block);
            self.incr();

            res.push(block.into());
        }
        res
    }
}

/// Hash function that generates a [`Seed`] and a [`Com`]mitment from a [`Key`] and an initialization vector [`IV`].
///
/// This function is applied on the leaves keys of the Tree-PRG/GGM-tree to generate the seeds and commitments.
/// This function corresponds to the H0 in the FAEST spec, defined page 16.
pub(crate) fn h0(x: Key, iv: IV) -> (Seed, Com) {
    // Hash x||iv to generate the Key
    let mut hasher = Shake128::default();
    hasher.update(&x);
    hasher.update(&iv);
    hasher.update(&[0u8]);

    let mut reader = hasher.finalize_xof();
    let mut seed = [u8::default(); SECURITY_PARAM / 8];
    let mut commitment = [u8::default(); (SECURITY_PARAM * 2) / 8];
    reader.read(seed.as_mut_slice());
    reader.read(commitment.as_mut_slice());

    (seed, commitment)
}

/// Length of H1 hash in bytes.
pub(crate) const H1_LENGTH: usize = (SECURITY_PARAM / 8) * 2;

/// Hash digest for a collision-resistant hash function.
///
/// This is used for various purposes throughout the protocol.
#[derive(Clone, Copy, Default)]
pub(crate) struct H1([u8; H1_LENGTH]);

impl H1 {
    /// Compute the [`H1`] hash from input bytes.
    pub(crate) fn from_bytes(inp: &[u8]) -> H1 {
        let mut out = H1::default();

        let mut hasher = Shake128::default();
        hasher.update(inp);
        hasher.update(&[1u8]);

        hasher.finalize_xof_into(&mut out.0);
        out
    }

    /// Treat this hash digest as a commitment.
    pub(crate) fn into_com(self) -> Com {
        self.0
    }
}

impl AsRef<[u8; H1_LENGTH]> for H1 {
    fn as_ref(&self) -> &[u8; H1_LENGTH] {
        &self.0
    }
}

/// Hash function for the Fiat-Shamir challenges generated in the protocol.
///
/// This is `$H_2^j$` in FAEST spec
#[derive(Default)]
struct H2Hasher(Shake128);

impl H2Hasher {
    fn update(&mut self, data: &[u8]) {
        self.0.update(data);
    }

    fn finalize(mut self, out: &mut [u8]) {
        self.0.update(&[2u8]);
        self.0.finalize_xof_into(out);
    }
}

/// Length of 1st challenge in bytes.
pub(crate) const CHALL1_LENGTH: usize = (SECURITY_PARAM * 6) / 8;

/// First challenge
pub(crate) type Chall1 = [u8; CHALL1_LENGTH];

/// Make the first Fiat-Shamir challenge.
///
/// This computes `$H_2^1$` in FAEST spec.
pub(crate) fn h2_chall1(mu: &H1, hcom: &Com, corrections: &Corrections, iv: &IV) -> Chall1 {
    let mut hasher = H2Hasher::default();

    hasher.update(&mu.0);
    hasher.update(hcom);
    hasher.update(&corrections_to_bytes(corrections));
    hasher.update(iv);

    let mut out = [0u8; CHALL1_LENGTH];
    hasher.finalize(&mut out);
    out
}

/// Length of 2nd challenge in bytes.
pub(crate) const CHALL2_LENGTH: usize = (SECURITY_PARAM * 3 + 64) / 8;
/// Second challenge
pub(crate) type Chall2 = [u8; CHALL2_LENGTH];

/// This is `$H_2^2$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h_chall2(inp: &[u8]) -> Chall2 {
    let mut hasher = H2Hasher::default();

    hasher.update(inp);

    let mut out: Chall2 = [0u8; CHALL2_LENGTH]; // NOTE: default does not work here
    hasher.finalize(&mut out);
    out
}

/// Length of 3rd challenge in bytes.
pub(crate) const CHALL3_LENGTH: usize = SECURITY_PARAM / 8;
/// Third challenge.
pub(crate) type Chall3 = [u8; CHALL3_LENGTH];

/// Makes the third Fiat-Shamir challenge.
///
/// This computes `$H_2^3$` in FAEST spec.
#[allow(unused)]
pub(crate) fn h2_chall3(chall2: &Chall2, a_tilde: &F128b, b_tilde: &F128b) -> Chall3 {
    let mut hasher = H2Hasher::default();

    hasher.update(chall2);
    hasher.update(&a_tilde.to_bytes());
    hasher.update(&b_tilde.to_bytes());

    let mut out = Chall3::default();
    hasher.finalize(&mut out);
    out
}

/// Hash digest for randomness and IV generation.
///
/// This should incorporate secret information or randomness (e.g. that only
/// the verifier knows), to derive secret, per-proof values.
#[derive(Clone, Default)]
pub(crate) struct H3([u8; (SECURITY_PARAM + 128) / 8]);

impl H3 {
    /// Derive the [`H3`] hash from an input.
    #[allow(unused)]
    pub(crate) fn from_input(inp: &[u8]) -> Self {
        let mut hasher = Shake128::default();
        hasher.update(inp);

        // Append 0x3 for domain separation
        hasher.update(&[3u8]);
        let mut reader = hasher.finalize_xof();

        let mut out: H3 = Default::default();
        reader.read(out.as_mut());
        out
    }

    /// Derive the [`H3`] hash from an instance of `Shake128`, which we assume
    /// has already been updated with all relevant secret information.
    pub(crate) fn from_xof(mut xof: Shake128) -> Self {
        // Append 0x3 for domain separation
        xof.update(&[3u8]);

        let mut out: H3 = Default::default();
        xof.finalize_xof_into(out.as_mut());
        out
    }
}

impl AsRef<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_ref(&self) -> &[u8; SECURITY_PARAM / 8 + 128 / 8] {
        &self.0
    }
}

impl AsMut<[u8; SECURITY_PARAM / 8 + 128 / 8]> for H3 {
    fn as_mut(&mut self) -> &mut [u8; SECURITY_PARAM / 8 + 128 / 8] {
        &mut self.0
    }
}
