# See `.gitlab-ci.yml` and the contents of `etc/ci` for additional
# information on Swanky's 'true' CI configuration.

name: Swanky - Normal Tests
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+"
    branches: [dev]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Checkout Swanky
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=${{ github.workspace }}/etc/nix/pkgs.nix
      - name: Run quick checks (no benchmarks)
        run: |
          # Note: `--cache-dir` is required, but won't actually do
          # anything useful on a public GitHub runner (see
          # `etc/ci/target_dir_cache.py` for details), so we use
          # `/tmp`.
          ./swanky ci quick --cache-dir /tmp
